config/routes.rb
Rails.application.routes.draw do
  
  # users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # teams
  resources :teams, except: [:show] do
    member do
      post :select # set user's current team

      get :list_members, path: 'members'
      post :add_member, path: 'members'
      delete :remove_member, path: 'members'      
    end
  end

  # events
  root 'events#index'  
  resources :events do
    get 'go', on: :member
  end

  # admin
  post 'admin/toggle'  
  
end

app/views/partials/_navbar.haml
%nav.navbar.navbar-expand-lg.navbar-dark.justify-content-between{:style => "background: ##{current_team.try(:color) || '343A40'};"}
  .navbar-nav
    - if current_team.nil?
      %a.navbar-brand{:href => "/"}= t(:name)
    - else
      = link_to root_path, class: 'navbar-brand' do
        %img.team-icon.rounded.align-top.mr-1{src: current_team.logo.url(:icon), width: 30, height: 30}
        = current_team.name

  .navbar-nav
    - if user_signed_in?
      - if current_user.admin
        = link_to t(admin_enabled ? 'admin.disable' : 'admin.enable'), admin_toggle_path, class: 'nav-item btn btn-outline-light mr-3', method: :post
      = link_to t('teams.switch'), teams_path, class: 'nav-item btn btn-outline-light mr-3'
      %span.nav-item.navbar-text.text-light
        - if admin_enabled
          %span.badge.badge-danger= t('admin.badge')
        = current_user.display_name
    - else
      = link_to t(:sign_in), user_reddit_omniauth_authorize_path, class: 'nav-item btn btn-outline-light'