config/routes.rb
Rails.application.routes.draw do
  
  # users
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  # teams
  resources :teams, except: [:show] do
    member do
      post :select # set user's current team

      get :list_members, path: 'members'
      post :add_member, path: 'members'
      delete :remove_member, path: 'members'      
    end
  end

  # events
  root 'events#index'  
  resources :events do
    get 'go', on: :member
  end

  # admin
  post 'admin/toggle'  
  
end

app/models/event.rb
class Event
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug
  include Mongoid::Paperclip
  include Scram::DSL::ModelConditions

  belongs_to :team
  belongs_to :creator, class_name: 'User'

  field :name, type: String
  validates :name, presence: true, length: { maximum: 120 }

  field :description, type: String
  validates :description, presence: true, length: { minimum: 16, maximum: 120 }

  field :url, type: String
  validates :url, presence: true, length: { minimum: 4, maximum: 24 }
  slug :url

  # ID of the live thread on Reddit
  field :reddit_id, type: String
  validates :reddit_id, presence: true, length: { minimum: 12 }

  has_mongoid_attached_file :image, styles: {
    :original => ['1920x1680>', :jpg],
    :social => ['952x498#', :png]
  }
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

  scram_define do
    condition :members do |event|
      event.team.send("*members")
    end
    condition :managers do |event|
      event.team.send("*managers")
    end
  end

  def reddit_url
    "https://reddit.com/live/#{reddit_id}"
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :get_event, only: [:go, :show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]
  before_action :select_team, only: [:index, :new, :create]

  def go
  end

  def index
    @events = current_team.events
  end

  def show
  end

  def new
    @event = Event.new(team: current_team)
    authorize @event
  end

  def edit
    authorize @event
  end

  def create
    @event = Event.new(params.require(:event).permit(:name, :url, :description, :reddit_id, :image).merge!(team: current_team))
    @event.creator = current_user
    authorize @event
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def update
    authorize @event
    if @event.update(params.require(:event).permit(:name, :description, :image))
      redirect_to @event
    else
      render 'edit'
    end
  end

  def destroy
    authorize @event
    @event.destroy
    redirect_to event_path
  end

  private
    def get_event
      @event = Event.find(params[:id])
    end

end

app/helpers/events_helper.rb
module EventsHelper

  def detail_for_event(event)
    creator = event.creator.try(:display_name) || t('no_user')
    time = event.created_at? ? time_ago_in_words(event.created_at) : t('no_time')
    t('events.detail', creator: creator, time: time)
  end

end

app/views/events/_form.haml
- if @event.errors.any?
  .alert.alert-warning
    = t('events.invalid')
    %ul
      - @event.errors.full_messages.each do |error|
        %li= error

= form_for @event do |f|
  .form-group
    = f.label :name, t('events.name')
    = f.text_field :name, class: 'form-control'
  .form-group
    = f.label :url, t('events.url')
    - unless %w{edit update}.include? action_name
      .input-group
        %span.input-group-addon https://liveteam.org/go/
        = f.text_field :url, class: 'form-control'
    - else
      %br
      = "https://liveteam.org/go/#{@event.url}"
  .form-group
    = f.label :reddit_id, t('events.reddit_id')
    - unless %w{edit update}.include? action_name
      .input-group
        %span.input-group-addon https://reddit.com/live/
        = f.text_field :reddit_id, class: 'form-control'
    - else
      %br
      = link_to @event.reddit_url, @event.reddit_url
  .form-group
    = f.label :image, t('events.image')
    = f.file_field :image, class: 'form-control'
  .form-group
    = f.label :description, t('events.description')
    = f.text_area :description, class: 'form-control'

  = f.submit class: 'btn btn-primary'

app/views/events/edit.haml
.container.content
  = render 'form'

app/views/events/go.haml
- content_for :meta do
  -# Redirect for users
  %meta{'http-equiv': 'refresh', 'content': "0; url=#{@event.reddit_url}"}

  -# Facebook/Open Graph
  %meta{property: 'og:title', content: @event.name}
  %meta{property: 'og:description', content: @event.description}
  %meta{property: 'og:image', content: @event.image.url(:social)}
  %meta{property: 'og:type', content: 'article'}
  %meta{property: 'og:site_name', content: @event.team.name}

  -# Twitter Cards
  %meta{property: 'twitter:card', content: 'summary_large_image'}
  %meta{property: 'twitter:title', content: @event.name}
  %meta{property: 'twitter:description', content: @event.description}
  %meta{property: 'twitter:image', content: @event.image.url(:social)}
  %meta{property: 'twitter:site', content: @event.team.name}

.container.content
  = link_to t('events.redirect'), @event.reddit_url, class: 'btn btn-primary'

app/views/events/index.haml
= render 'teams/header', team: current_team

.container.content
  .row
    - if current_user.can? :create, Event.new(team: current_team)
      .col-12
        .card.event-card.creation-card.text-center
          .card-body
            - if @events.empty?
              %center= t('events.none')
            = link_to t('events.create'), new_event_path, class: 'btn btn-primary'
    - @events.order_by(:created_at => :desc).each do |event|
      .col-12
        .card.event-card
          .card-body
            = link_to event do
              %h4.card-title= event.name
            %p.card-text= event.description
            = link_to t('events.view_reddit'), event.reddit_url, class: 'card-link'
          .card-footer.text-muted= detail_for_event(event)

app/views/events/show.haml
.container.content
  %img{src: @event.image.url}
  %h1= @event.name
  %p.lead= @event.description
  - if current_user.can? :edit, @event
    = link_to t('events.edit'), edit_event_path(@event), class: 'btn btn-primary'
  = link_to t('events.view_reddit'), @event.reddit_url, class: 'btn btn-link'